// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Force migrations to use the DIRECT connection if available
const isMigration = process.argv.join(" ").includes("migrate");
const dbUrl = isMigration 
  ? (process.env["DIRECT_URL"] || process.env["DATABASE_URL"])
  : process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
